# Generated by Django 5.1.4 on 2024-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NormalUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_order', models.IntegerField()),
            ],
            options={
                'db_table': 'UserName',
                'managed': False,
            },
        ),
    ]
